name: DiscordBridge
version: ${version}
description: Bridges chat between Minecraft and Discord

author: Jacob Gillespie
website: https://github.com/the-obsidian/DiscordBridge

main: gg.obsidian.discordbridge.DiscordBridge

